site_name: NCBI E-Utilities
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - search.highlight
    - content.tabs.link
extra_css:
          - stylesheets/extra.css
