site_name: NCBI E-Utilities
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - search.highlight
    - content.tabs.link

nav:
  - Home: 'index.md'
  - eu_quick:
    - eu_quick.md
    - eu_reference.md
    - ed_pubmed.md